//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public Nullable<bool> del_inv { get; set; }
        public Nullable<bool> add_inv { get; set; }
        public string invNum { get; set; }
        public string name { get; set; }
        public string date { get; set; }
        public string serialNum { get; set; }
        public string user { get; set; }
        public string ipaddress { get; set; }
        public string computerName { get; set; }
        public string type { get; set; }
        public Nullable<double> cost { get; set; }
    }
}
